name: amap_core_fluttify
description: An `Amap` Core Component, Powered By `Fluttify` Engine, A Dart Bindings Generator For Native SDK.
version: 0.15.0-dev.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_core_fluttify

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify: ^0.13.0-dev.0
  core_location_fluttify: ^0.7.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_core_fluttify
        pluginClass: AmapCoreFluttifyPlugin
      ios:
        pluginClass: AmapCoreFluttifyPlugin